import type { Metadata } from 'next';
// import { Inter } from 'next/font/google'
import '../globals.css'

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'MentalPaddi',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-primary'>
          <p className='text-4xl font-bold text-center text-white m-20'>Mentalpaddi</p>
          {children}
      </body>
    </html>
  )
}
