import type { Metadata } from 'next';
// import { Inter } from 'next/font/google'
import '../globals.css'

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'MentalPaddi',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <div className='bg-primary min-h-full border-primary border-2'>
        <div className='p-20 text-center'>
          <p className='text-4xl font-bold text-center text-white'>Mentalpaddi</p>
          <p className='text-white font-light text-xs pt-1'>We are here for your Mind</p>
        </div>
          {children}
      </div>
  )
}
